@extends('layouts.public')
@section('title', 'Terms of Service')
@section('desc', 'The terms for using Cryptocoinex, a free practice trading simulator.')

@section('content')
<div class="wrap">
  <article class="legal">
    <div class="eyebrow">Legal</div>
    <h1>Terms of Service</h1>
    <div class="updated">Last updated {{ date('F Y') }}</div>

    <div class="note">
      <b>Important:</b> Cryptocoinex is an <b>educational trading simulator</b>, not a broker or financial
      service. All balances are virtual “USD” with <b>zero monetary value</b>. Nothing here is financial advice.
    </div>

    <p>These terms govern your use of Cryptocoinex. By creating an account or using the platform you agree to them.
      If you do not agree, please do not use the service.</p>

    <h2>1. What Cryptocoinex is (and isn't)</h2>
    <ul>
      <li>It is a <strong>practice simulator</strong> for learning to trade using virtual money.</li>
      <li>It is <strong>not</strong> a brokerage, exchange, investment platform or money-transmission service.</li>
      <li>No real funds are ever deposited, held, traded or withdrawn. “USD” cannot be redeemed for anything.</li>
    </ul>

    <h2>2. Not financial advice</h2>
    <p>All content — including prices, charts, lessons, tournaments and results — is provided for education and
      entertainment only. It does not constitute financial, investment or trading advice. Real markets carry real
      risk; success in the simulator does not indicate future results in any real market.</p>

    <h2>3. Your account</h2>
    <ul>
      <li>You are responsible for keeping your login credentials secure.</li>
      <li>Provide accurate information and keep your account details up to date.</li>
      <li>You may reset your virtual balance or fully wipe your account data at any time.</li>
    </ul>

    <h2>4. Acceptable use</h2>
    <p>You agree not to misuse the platform — including attempting to break, overload, reverse-engineer or gain
      unauthorised access to it, or using it for any unlawful purpose. We may suspend or remove accounts that violate these terms.</p>

    <h2>5. Simulated market data</h2>
    <p>Prices shown are either generated by our simulation engine or based on delayed/cached public market data.
      They are provided “as is” and may not reflect real-time prices on any exchange.</p>

    <h2>6. Availability</h2>
    <p>We aim to keep Cryptocoinex available and reliable, but we provide it “as is” without warranties of any kind
      and may change, suspend or discontinue features at any time.</p>

    <h2>7. Limitation of liability</h2>
    <p>Because Cryptocoinex involves no real money and is provided free for educational use, to the maximum extent
      permitted by law we are not liable for any loss arising from your use of the platform.</p>

    <h2>8. Changes to these terms</h2>
    <p>We may update these terms from time to time. Continued use after changes means you accept the updated terms.</p>

    <h2>9. Contact</h2>
    <p>Questions? Reach us through the in-app help section. See also our
      <a href="{{ route('privacy') }}">Privacy Policy</a>.</p>
  </article>
</div>
@endsection
